name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs for the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: recepti
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=30s --health-timeout=5s --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'      # Specify Java version
            distribution: 'temurin'  # Correct distribution
            java-package: jdk
            check-latest: false

      # Cache dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 21
          maven-version: '3.x'
          distribution: ''

      # Run tests
      - name: Run tests
        run: mvn clean install

      # Build the project
      - name: Build the project
        run: mvn package -DskipTests=true

    # Deploy (if needed)
    # You can add deployment steps here (e.g., uploading to a server, Docker container, etc.)

